const featureIdMap = {
    9: "Tennis court",
    58: "Padel court",
    26: "Skiing",
    100: "Ski school",
    2: "Free parking",
    46: "Free parking",
    160: "Free parking",
    75: "Car hire",
    76: "Bicycle rental",
    447: "Bicycle rental",
    182: "Electric vehicle charging station",
    115: "Restaurant",
    116: "Restaurant",
    24: "Continental breakfast",
    6: "Meeting/banquet facilities",
    7: "Bar",
    219: "Coffee house on site",
    12: "Golf course",
    97: "Mini golf",
    29: "Games room",
    11: "Fitness center",
    253: "Fitness center",
    255: "Fitness center",
    61: "Windsurfing",
    70: "Hiking",
    77: "Bowling",
    82: "Diving",
    86: "Horse riding",
    137: "Water sport facilities",
    258: "Kids pool",
    195: "Heated pool",
    103: "Indoor pool",
    121: "Indoor pool",
    122: "Indoor pool",
    104: "Outdoor pool",
    119: "Outdoor pool",
    120: "Outdoor pool",
    301: "Outdoor pool",
    433: "Outdoor pool",
    241: "Steam room",
    71: "Chapel/shrine",
    30: "Casino",
    114: "Private beach area",
    302: "Private beach area",
    126: "Nightclub/DJ",
    20: "Business center",
    14: "Green areas",
    16: "Non-smoking rooms",
    22: "Laundry",
    28: "Family rooms",
    414: "Bingo",
    148: "Water park",
    138: "Hot spring bath",
    431: "Hot spring bath",
    59: "Karaoke",
    63: "Jacuzzi",
    10: "Sauna",
    54: "Spa and wellness center",
    240: "Spa and wellness center",
    242: "Spa and wellness center",
    244: "Spa and wellness center",
    56: "Kids play area",
    25: "Facilities for disabled guests",
    185: "Wheelchair accessible",
    211: "Visual aids: braille",
    212: "Visual aids: tactile signs",
    8: "24-hour front desk",
    124: "Concierge service",
    27: "Barber/beauty shop",
    167: "Barber/beauty shop",
    78: "Tour desk",
    4: "Pets allowed",
    91: "Luggage storage",
    47: "Free Wi-Fi",
    96: "Free Wi-Fi",
    107: "Free Wi-Fi",
    163: "Free Wi-Fi",
    418: "24-hour security",
    15: "Terrace",
    64: "Soundproof rooms",
    5: "Room service",
    17: "Airport shuttle",
    128: "Airport shuttle",
    129: "Airport shuttle",
    139: "Airport shuttle",
    140: "Airport shuttle",
    304: "Airport shuttle",
  };
  
  export default featureIdMap;