import {AirportShuttleIcon, BarberIcon, BarIcon, BeachIcon, BikeIcon, BingoIcon, BowlingIcon, BusinessIcon, CarIcon, CasinoIcon, ChurchIcon, CoffeeIcon, ConciergeIcon, ConferenceIcon, DisabledIcon, DivingIcon, ElectricCarIcon, FamilyIcon, FitnessIcon, GamesIcon, GardenIcon, GolfIcon, HikingIcon, HorseIcon, HotSpringIcon, JacuzziIcon, KaraokeIcon, KidsAreaIcon, LaundryIcon, LuggageIcon, MultilingualIcon, NightclubIcon, ParkingIcon, PetsIcon, PoolIcon, ReceptionIcon, RestaurantIcon, RoomServiceIcon, SecurityIcon, SkiIcon, SmokingIcon, SoundIcon, SpaIcon, SteamIcon, TenisIcon, TerraceIcon, TourIcon, VisualAidsIcon, WaterParkIcon, WifiIcon, WindsurfIcon } from "../icons/FeaturesIcons";
import { 
  AirportShuttleIconDark, 
  BarberIconDark, 
  BarIconDark, 
  BeachIconDark, 
  BikeIconDark, 
  BingoIconDark, 
  BowlingIconDark, 
  BusinessIconDark, 
  CarIconDark, 
  CasinoIconDark, 
  ChurchIconDark, 
  CoffeeIconDark, 
  ConciergeIconDark, 
  ConferenceIconDark, 
  DisabledIconDark, 
  DivingIconDark, 
  ElectricCarIconDark, 
  FamilyIconDark, 
  FitnessIconDark, 
  GamesIconDark, 
  GardenIconDark, 
  GolfIconDark, 
  HikingIconDark, 
  HorseIconDark, 
  HotSpringIconDark, 
  JacuzziIconDark, 
  KaraokeIconDark, 
  KidsAreaIconDark, 
  LaundryIconDark, 
  LuggageIconDark, 
  MultilingualIconDark, 
  NightclubIconDark, 
  ParkingIconDark, 
  PetsIconDark, 
  PoolIconDark, 
  ReceptionIconDark, 
  RestaurantIconDark, 
  RoomServiceIconDark, 
  SecurityIconDark, 
  SkiIconDark, 
  SmokingIconDark, 
  SoundIconDark, 
  SpaIconDark, 
  SteamIconDark, 
  TenisIconDark, 
  TerraceIconDark, 
  TourIconDark, 
  VisualAidsIconDark, 
  WaterParkIconDark, 
  WifiIconDark, 
  WindsurfIconDark 
} from "../icons/FeaturesIconsDark";

const featureIconMap = {
    "Tennis court": <TenisIcon />,
    "Padel court": <TenisIcon />,
    "Skiing": <SkiIcon />,
    "Ski school": <SkiIcon />,
    "Free parking": <ParkingIcon />,
    "Car hire": <CarIcon />,
    "Bicycle rental": <BikeIcon />,
    "Electric vehicle charging station": <ElectricCarIcon />,
    "Restaurant": <RestaurantIcon />,
    "Continental breakfast": <RestaurantIcon />,
    "Meeting/banquet facilities": <RestaurantIcon />,
    "Bar": <BarIcon />,
    "Coffee house on site": <CoffeeIcon />,
    "Golf course": <GolfIcon />,
    "Mini golf": <GolfIcon />,
    "Games room": <GamesIcon />,
    "Fitness center": <FitnessIcon />,
    "Windsurfing": <WindsurfIcon />,
    "Hiking": <HikingIcon />,
    "Bowling": <BowlingIcon />,
    "Diving": <DivingIcon />,
    "Horse riding": <HorseIcon />,
    "Water sport facilities": <PoolIcon />,
    "Kids pool": <PoolIcon />,
    "Heated pool": <PoolIcon />,
    "Indoor pool": <PoolIcon />,
    "Outdoor pool": <PoolIcon />,
    "Steam room": <SteamIcon />,
    "Chapel/shrine": <ChurchIcon />,
    "Casino": <CasinoIcon />,
    "Private beach area": <BeachIcon />,
    "Nightclub/DJ": <NightclubIcon />,
    "Business center": <BusinessIcon />,
    "Green areas": <GardenIcon />,
    "Non-smoking rooms": <SmokingIcon />,
    "Laundry": <LaundryIcon />,
    "Family rooms": <FamilyIcon />,
    "Bingo": <BingoIcon />,
    "Water park": <WaterParkIcon />,
    "Hot spring bath": <HotSpringIcon />,
    "Karaoke": <KaraokeIcon />,
    "Conference room": <ConferenceIcon />,
    "Jacuzzi": <JacuzziIcon />,
    "Sauna": <SteamIcon />,
    "Spa and wellness center": <SpaIcon />,
    "Kids play area": <KidsAreaIcon />,
    "Facilities for disabled guests": <DisabledIcon />,
    "Wheelchair accessible": <DisabledIcon />,
    "Visual aids: braille": <VisualAidsIcon />,
    "Visual aids: tactile signs": <VisualAidsIcon />,
    "Multilingual staff": <MultilingualIcon />,
    "24-hour front desk": <ReceptionIcon />,
    "Concierge service": <ConciergeIcon />,
    "Barber/beauty shop": <BarberIcon />,
    "Tour desk": <TourIcon />,
    "Pets allowed": <PetsIcon />,
    "Luggage storage": <LuggageIcon />,
    "Free Wi-Fi": <WifiIcon />,
    "24-hour security": <SecurityIcon />,
    "Terrace": <TerraceIcon />,
    "Soundproof rooms": <SoundIcon />,
    "Room service": <RoomServiceIcon />,
    "Airport shuttle": <AirportShuttleIcon />,
  };
  
  const featureIconMapDark = {
    "Tennis court": <TenisIconDark />,
    "Padel court": <TenisIconDark />,
    "Skiing": <SkiIconDark />,
    "Ski school": <SkiIconDark />,
    "Free parking": <ParkingIconDark />,
    "Car hire": <CarIconDark />,
    "Bicycle rental": <BikeIconDark />,
    "Electric vehicle charging station": <ElectricCarIconDark />,
    "Restaurant": <RestaurantIconDark />,
    "Continental breakfast": <RestaurantIconDark />,
    "Meeting/banquet facilities": <RestaurantIconDark />,
    "Bar": <BarIconDark />,
    "Coffee house on site": <CoffeeIconDark />,
    "Golf course": <GolfIconDark />,
    "Mini golf": <GolfIconDark />,
    "Games room": <GamesIconDark />,
    "Fitness center": <FitnessIconDark />,
    "Windsurfing": <WindsurfIconDark />,
    "Hiking": <HikingIconDark />,
    "Bowling": <BowlingIconDark />,
    "Diving": <DivingIconDark />,
    "Horse riding": <HorseIconDark />,
    "Water sport facilities": <PoolIconDark />,
    "Kids pool": <PoolIconDark />,
    "Heated pool": <PoolIconDark />,
    "Indoor pool": <PoolIconDark />,
    "Outdoor pool": <PoolIconDark />,
    "Steam room": <SteamIconDark />,
    "Chapel/shrine": <ChurchIconDark />,
    "Casino": <CasinoIconDark />,
    "Private beach area": <BeachIconDark />,
    "Nightclub/DJ": <NightclubIconDark />,
    "Business center": <BusinessIconDark />,
    "Green areas": <GardenIconDark />,
    "Non-smoking rooms": <SmokingIconDark />,
    "Laundry": <LaundryIconDark />,
    "Family rooms": <FamilyIconDark />,
    "Bingo": <BingoIconDark />,
    "Water park": <WaterParkIconDark />,
    "Hot spring bath": <HotSpringIconDark />,
    "Karaoke": <KaraokeIconDark />,
    "Conference room": <ConferenceIconDark />,
    "Jacuzzi": <JacuzziIconDark />,
    "Sauna": <SteamIconDark />,
    "Spa and wellness center": <SpaIconDark />,
    "Kids play area": <KidsAreaIconDark />,
    "Facilities for disabled guests": <DisabledIconDark />,
    "Wheelchair accessible": <DisabledIconDark />,
    "Visual aids: braille": <VisualAidsIconDark />,
    "Visual aids: tactile signs": <VisualAidsIconDark />,
    "Multilingual staff": <MultilingualIconDark />,
    "24-hour front desk": <ReceptionIconDark />,
    "Concierge service": <ConciergeIconDark />,
    "Barber/beauty shop": <BarberIconDark />,
    "Tour desk": <TourIconDark />,
    "Pets allowed": <PetsIconDark />,
    "Luggage storage": <LuggageIconDark />,
    "Free Wi-Fi": <WifiIconDark />,
    "24-hour security": <SecurityIconDark />,
    "Terrace": <TerraceIconDark />,
    "Soundproof rooms": <SoundIconDark />,
    "Room service": <RoomServiceIconDark />,
    "Airport shuttle": <AirportShuttleIconDark />,
  };


  export {featureIconMap, featureIconMapDark};
  