import {AirportShuttleIcon, BarberIcon, BarIcon, BeachIcon, BikeIcon, BingoIcon, BowlingIcon, BusinessIcon, CarIcon, CasinoIcon, ChurchIcon, CoffeeIcon, ConciergeIcon, ConferenceIcon, DisabledIcon, DivingIcon, ElectricCarIcon, FamilyIcon, FitnessIcon, GamesIcon, GardenIcon, GolfIcon, HikingIcon, HorseIcon, HotSpringIcon, JacuzziIcon, KaraokeIcon, KidsAreaIcon, LaundryIcon, LuggageIcon, MultilingualIcon, NightclubIcon, ParkingIcon, PetsIcon, PoolIcon, ReceptionIcon, RestaurantIcon, RoomServiceIcon, SecurityIcon, SkiIcon, SmokingIcon, SoundIcon, SpaIcon, SteamIcon, TenisIcon, TerraceIcon, TourIcon, VisualAidsIcon, WaterParkIcon, WifiIcon, WindsurfIcon } from "../icons/FeaturesIcons";

const featureIconMap = {
    "Tennis court": <TenisIcon />,
    "Padel court": <TenisIcon />,
    "Skiing": <SkiIcon />,
    "Ski school": <SkiIcon />,
    "Free parking": <ParkingIcon />,
    "Car hire": <CarIcon />,
    "Bicycle rental": <BikeIcon />,
    "Electric vehicle charging station": <ElectricCarIcon />,
    "Restaurant": <RestaurantIcon />,
    "Continental breakfast": <RestaurantIcon />,
    "Meeting/banquet facilities": <RestaurantIcon />,
    "Bar": <BarIcon />,
    "Coffee house on site": <CoffeeIcon />,
    "Golf course": <GolfIcon />,
    "Mini golf": <GolfIcon />,
    "Games room": <GamesIcon />,
    "Fitness center": <FitnessIcon />,
    "Windsurfing": <WindsurfIcon />,
    "Hiking": <HikingIcon />,
    "Bowling": <BowlingIcon />,
    "Diving": <DivingIcon />,
    "Horse riding": <HorseIcon />,
    "Water sport facilities": <PoolIcon />,
    "Kids pool": <PoolIcon />,
    "Heated pool": <PoolIcon />,
    "Indoor pool": <PoolIcon />,
    "Outdoor pool": <PoolIcon />,
    "Steam room": <SteamIcon />,
    "Chapel/shrine": <ChurchIcon />,
    "Casino": <CasinoIcon />,
    "Private beach area": <BeachIcon />,
    "Nightclub/DJ": <NightclubIcon />,
    "Business center": <BusinessIcon />,
    "Green areas": <GardenIcon />,
    "Non-smoking rooms": <SmokingIcon />,
    "Laundry": <LaundryIcon />,
    "Family rooms": <FamilyIcon />,
    "Bingo": <BingoIcon />,
    "Water park": <WaterParkIcon />,
    "Hot spring bath": <HotSpringIcon />,
    "Karaoke": <KaraokeIcon />,
    "Conference room": <ConferenceIcon />,
    "Jacuzzi": <JacuzziIcon />,
    "Sauna": <SteamIcon />,
    "Spa and wellness center": <SpaIcon />,
    "Kids play area": <KidsAreaIcon />,
    "Facilities for disabled guests": <DisabledIcon />,
    "Wheelchair accessible": <DisabledIcon />,
    "Visual aids: braille": <VisualAidsIcon />,
    "Visual aids: tactile signs": <VisualAidsIcon />,
    "Multilingual staff": <MultilingualIcon />,
    "24-hour front desk": <ReceptionIcon />,
    "Concierge service": <ConciergeIcon />,
    "Barber/beauty shop": <BarberIcon />,
    "Tour desk": <TourIcon />,
    "Pets allowed": <PetsIcon />,
    "Luggage storage": <LuggageIcon />,
    "Free Wi-Fi": <WifiIcon />,
    "24-hour security": <SecurityIcon />,
    "Terrace": <TerraceIcon />,
    "Soundproof rooms": <SoundIcon />,
    "Room service": <RoomServiceIcon />,
    "Airport shuttle": <AirportShuttleIcon />,
  };
  
  export default featureIconMap;
  